// Stellar Testnet Constants
export const TESTNET_USDC_ISSUER = "GBBD47IF6LWK7P7MDEVSCWR7DPUWV3NY3DTQEVFL4NAT4AQH3ZLLFLA5";
export const TESTNET_NETWORK_PASSPHRASE = "Test SDF Network ; September 2015";
